### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Grinch** [AlmuraDev/Backpack#2]
## Initial release
- [x] H2 support
- [x] Open
  - **Command**: `/backpack`
  - **Permission(s)**:
    - `backpack.command.open`
- [x] Upgrade/Downgrade system
  - **Description**: Allows up/downgrading from 9 to 54 and vice versa. 
  - **Command**: `/backpack [upgrade|downgrade]`
  - **Permission(s)**:
    - `backpack.command.downgrade`
    - `backpack.command.upgrade`
    - `backpack.<world_name>.size.default.<9:54>` (defaults to 9)
    - `backpack.<world_name>.size.min.<9:54>` (defaults to 9)
    - `backpack.<world_name>.size.max.<9:54>` (defaults to 54)
- [x] Drop items on death
  - **Description**: Drops items around the player as if it was from the main inventory. Bypass permission prevents dropping of items.
  - **Permission(s)**:
    - `backpack.<world_name>.death.bypass`
- [x] View other backpacks
  - **Description**: Opens a backpack for the specified player. If they don't have the modify permission they get a generic backpack with the same content as the original. Modify permission will allow them to make changes to the backpack's content.
  - **Command**: `/backpack view <player>`
  - **Permission(s)**:
    - `backpack.command.view.modify`
- [x] Reload command
  - **Description**: Reloads the configuration file. Useful for quick edits to the blacklist.
  - **Command**: `/backpack reload`
  - **Permission(s)**:
    - `backpack.command.reload`
- [x] Economy support
- [x] Events
  - `BackpackEvent`
    - `BackpackEvent.Create`
    - `BackpackEvent.Load`
    - `BackpackEvent.Save`
    - `BackpackEvent.Resize`
  - `SlotEvent`
    - `SlotEvent.Load`
    - `SlotEvent.Save`
- [ ] World Share
- [ ] API
- [ ] Cleanup
- [ ] Setup Travis-CI to deploy builds to Releases on GitHub
## Future
- [ ] Custom SQL database support
- [ ] Overflow ability (Not confirmed)
- [ ] Blacklisting of items from backpack on per-world basis
  - **Description**: Prevents items from entering a backpack.
  - **Command**: `/backpack blacklist`
  - **Permission(s)**:
    - `backpack.<world_name>.blacklist.bypass`
